CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_DISPLAY=y
CONFIG_WS2812_STRIP=n

#CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=186
#CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=25
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=25



#CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=2
#CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=2
#CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=2
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=2
#CONFIG_ZMK_RGB_UNDERGLOW_EXT_EFFECTS=n
#CONFIG_ZMK_RGB_UNDERGLOW_HUE=186
#CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
#CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3
